class OfflineIngredient {
  final int id;
  final String key, nameEn, nameAr, nameRo;
  final double calories, protein, carbs, fat, fiber;
  const OfflineIngredient(this.id, this.key, this.nameEn, this.nameAr, this.nameRo,
      this.calories, this.protein, this.carbs, this.fat, this.fiber);
}

class OfflineRecipeIngredient {
  final int ingredientId;
  final double quantityG;
  const OfflineRecipeIngredient(this.ingredientId, this.quantityG);
}

class OfflineRecipe {
  final int id;
  final String nameEn, nameAr, nameRo, cuisine;
  final int servings, prepMinutes, cookMinutes;
  final List<OfflineRecipeIngredient> ingredients;
  const OfflineRecipe(this.id, this.nameEn, this.nameAr, this.nameRo, this.cuisine,
      this.servings, this.prepMinutes, this.cookMinutes, this.ingredients);
}


const offlineIngredients = <OfflineIngredient>[
  OfflineIngredient(1,'chicken','Chicken breast, cooked','دجاج','Murghi',165,31,0,3.6,0),
  OfflineIngredient(2,'potato','Potato','بطاطا','Aloo',77,2,17,0.1,2.2),
  OfflineIngredient(3,'onion','Onion','بصل','Pyaaz',40,1.1,9.3,0.1,1.7),
  OfflineIngredient(4,'tomato','Tomato','بندورة','Tamatar',18,0.9,3.9,0.2,1.2),
  OfflineIngredient(5,'lentils_brown','Brown lentils, dry','عدس بني','Masoor Dal',352,24.6,63.4,1.1,10.7),
  OfflineIngredient(6,'bulgur','Bulgur, dry','برغل','Bulgur',342,12.3,75.9,1.3,18.3),
  OfflineIngredient(7,'rice','White rice, dry','أرز','Chawal',365,7.1,80,0.7,1.3),
  OfflineIngredient(8,'yogurt','Plain whole yogurt','لبن','Dahi',61,3.5,4.7,3.3,0),
  OfflineIngredient(9,'chickpeas','Chickpeas, cooked','حمص','Chana',164,8.9,27.4,2.6,7.6),
  OfflineIngredient(10,'olive_oil','Olive oil','زيت زيتون','Zait Zaytoon',884,0,0,100,0),
  OfflineIngredient(11,'egg','Whole egg','بيض','Anda',143,12.6,0.7,9.5,0),
  OfflineIngredient(12,'garlic','Garlic','ثوم','Lehsan',149,6.4,33.1,0.5,2.1),
  OfflineIngredient(13,'lemon','Lemon juice','عصير ليمون','Nimbu',22,0.4,6.9,0.2,0.3),
  OfflineIngredient(14,'spinach','Spinach','سبانخ','Palak',23,2.9,3.6,0.4,2.2),
  OfflineIngredient(15,'beef','Lean beef, cooked','لحم بقري','Gosht',217,26.1,0,11.8,0),
  OfflineIngredient(16,'lamb','Lamb, cooked','لحم غنم','Mutton',258,25.6,0,16.5,0),
  OfflineIngredient(17,'minced_beef','Ground beef, cooked','لحم مفروم','Qeema',254,26,0,17,0),
  OfflineIngredient(18,'flour','Wheat flour','طحين','Aata',364,10.3,76.3,1,2.7),
  OfflineIngredient(19,'whole_wheat_flour','Whole wheat flour','طحين قمح كامل','Chakki Aata',340,13.2,72,2.5,10.7),
  OfflineIngredient(20,'butter','Butter','زبدة','Makhan',717,0.9,0.1,81.1,0),
  OfflineIngredient(21,'ghee','Ghee','سمن','Ghee',900,0,0,100,0),
  OfflineIngredient(22,'milk','Whole milk','حليب','Doodh',61,3.2,4.8,3.3,0),
  OfflineIngredient(23,'cream','Heavy cream','كريمة','Cream',340,2.8,2.8,36,0),
  OfflineIngredient(24,'cucumber','Cucumber','خيار','Kheera',15,0.7,3.6,0.1,0.5),
  OfflineIngredient(25,'bell_pepper','Bell pepper','فليفلة','Shimla Mirch',31,1,6,0.3,2.1),
  OfflineIngredient(26,'green_chili','Green chili','فلفل أخضر','Hari Mirch',40,2,9,0.2,1.5),
  OfflineIngredient(27,'ginger','Ginger','زنجبيل','Adrak',80,1.8,17.8,0.8,2),
  OfflineIngredient(28,'coriander','Fresh coriander','كزبرة','Dhania',23,2.1,3.7,0.5,2.8),
  OfflineIngredient(29,'parsley','Parsley','بقدونس','Parsley',36,3,6.3,0.8,3.3),
  OfflineIngredient(30,'mint','Fresh mint','نعناع','Podina',44,3.3,8.4,0.7,6.8),
  OfflineIngredient(31,'peas','Green peas','بازلاء','Matar',81,5.4,14.5,0.4,5.1),
  OfflineIngredient(32,'carrot','Carrot','جزر','Gajar',41,0.9,9.6,0.2,2.8),
  OfflineIngredient(33,'cauliflower','Cauliflower','قرنبيط','Phool Gobi',25,1.9,5,0.3,2),
  OfflineIngredient(34,'eggplant','Eggplant','باذنجان','Baingan',25,1,5.9,0.2,3),
  OfflineIngredient(35,'okra','Okra','بامية','Bhindi',33,1.9,7.5,0.2,3.2),
  OfflineIngredient(36,'zucchini','Zucchini','كوسا','Tori',17,1.2,3.1,0.3,1),
  OfflineIngredient(37,'cabbage','Cabbage','ملفوف','Band Gobi',25,1.3,5.8,0.1,2.5),
  OfflineIngredient(38,'kidney_beans','Kidney beans, cooked','فاصولياء حمراء','Rajma',127,8.7,22.8,0.5,6.4),
  OfflineIngredient(39,'black_gram','Black gram, dry','ماش أسود','Urad Dal',341,25.2,58.9,1.6,18.3),
  OfflineIngredient(40,'mung_beans','Mung beans, dry','ماش أخضر','Moong Dal',347,23.9,62.6,1.2,16.3),
  OfflineIngredient(41,'split_chickpeas','Split chickpeas, dry','حمص مجروش','Chana Dal',364,20.8,60.7,5.6,17.4),
  OfflineIngredient(42,'red_lentils','Red lentils, dry','عدس أحمر','Masoor Dal Red',352,24.6,63.4,1.1,10.7),
  OfflineIngredient(43,'fish_white','White fish, cooked','سمك أبيض','Machhli',128,26,0,2.7,0),
  OfflineIngredient(44,'salmon','Salmon, cooked','سلمون','Salmon',206,22,0,12,0),
  OfflineIngredient(45,'tuna','Tuna, canned in water','تونا','Tuna',116,25.5,0,0.8,0),
  OfflineIngredient(46,'shrimp','Shrimp, cooked','روبيان','Jhinga',99,24,0.2,0.3,0),
  OfflineIngredient(47,'pasta','Pasta, dry','معكرونة','Pasta',371,13,75,1.5,3.2),
  OfflineIngredient(48,'bread','White bread','خبز أبيض','Bread',266,8.9,49.4,3.3,2.7),
  OfflineIngredient(49,'whole_grain_bread','Whole grain bread','خبز قمح كامل','Brown Bread',247,13,41,4.2,7),
  OfflineIngredient(50,'cheese','Cheddar cheese','جبنة','Cheese',403,24.9,1.3,33.1,0),
  OfflineIngredient(51,'feta','Feta cheese','جبنة فيتا','Feta',264,14.2,4.1,21.3,0),
  OfflineIngredient(52,'mozzarella','Mozzarella','موزاريلا','Mozzarella',280,28,3.1,17,0),
  OfflineIngredient(53,'parmesan','Parmesan','بارميزان','Parmesan',431,38,4.1,29,0),
  OfflineIngredient(54,'oats','Oats, dry','شوفان','Jai',389,16.9,66.3,6.9,10.6),
  OfflineIngredient(55,'apple','Apple','تفاح','Seb',52,0.3,13.8,0.2,2.4),
  OfflineIngredient(56,'banana','Banana','موز','Kela',89,1.1,22.8,0.3,2.6),
  OfflineIngredient(57,'orange','Orange','برتقال','Santara',47,0.9,11.8,0.1,2.4),
  OfflineIngredient(58,'dates','Dates','تمر','Khajoor',282,2.5,75,0.4,8),
  OfflineIngredient(59,'walnuts','Walnuts','جوز','Akhrot',654,15.2,13.7,65.2,6.7),
  OfflineIngredient(60,'almonds','Almonds','لوز','Badam',579,21.2,21.6,49.9,12.5),
  OfflineIngredient(61,'pine_nuts','Pine nuts','صنوبر','Chilgoza',673,13.7,13.1,68.4,3.7),
  OfflineIngredient(62,'tahini','Tahini','طحينة','Tahini',595,17,21,53.8,9.3),
  OfflineIngredient(63,'tomato_paste','Tomato paste','معجون طماطم','Tomato Paste',82,4.3,18.9,0.5,4.1),
  OfflineIngredient(64,'coconut_milk','Coconut milk','حليب جوز الهند','Nariyal Doodh',230,2.3,5.5,23.8,2.2),
  OfflineIngredient(65,'coconut','Coconut','جوز هند','Nariyal',354,3.3,15.2,33.5,9),
  OfflineIngredient(66,'sugar','Sugar','سكر','Cheeni',387,0,100,0,0),
  OfflineIngredient(67,'honey','Honey','عسل','Shehad',304,0.3,82.4,0,0.2),
  OfflineIngredient(68,'semolina','Semolina','سميد','Sooji',360,12.7,72.8,1.1,3.9),
  OfflineIngredient(69,'cornmeal','Cornmeal','دقيق ذرة','Makai Aata',370,7,79,3.9,7.3),
  OfflineIngredient(70,'beans_white','White beans, cooked','فاصولياء بيضاء','Safed Beans',139,9.7,25,0.4,6.3),
  OfflineIngredient(71,'green_beans','Green beans','فاصولياء خضراء','French Beans',31,1.8,7,0.2,2.7),
  OfflineIngredient(72,'mushroom','Mushrooms','فطر','Mushroom',22,3.1,3.3,0.3,1),
  OfflineIngredient(73,'broccoli','Broccoli','بروكلي','Broccoli',34,2.8,6.6,0.4,2.6),
  OfflineIngredient(74,'leek','Leek','كراث','Leek',61,1.5,14.2,0.3,1.8),
  OfflineIngredient(75,'celery','Celery','كرفس','Celery',14,0.7,3,0.2,1.6),
  OfflineIngredient(76,'beetroot','Beetroot','شمندر','Chukandar',43,1.6,10,0.2,2.8),
  OfflineIngredient(77,'avocado','Avocado','أفوكادو','Avocado',160,2,8.5,14.7,6.7),
  OfflineIngredient(78,'bacon','Bacon, cooked','لحم مقدد','Bacon',541,37,1.4,42,0),
  OfflineIngredient(79,'sausage','Sausage, cooked','نقانق','Sausage',301,12,2,27,0),
  OfflineIngredient(80,'stock','Chicken/vegetable stock','مرق','Yakhni',7,0.5,0.5,0.2,0),
];

const offlineRecipes = <OfflineRecipe>[
  OfflineRecipe(1,'Chicken Biryani','برياني دجاج','Chicken Biryani','Pakistani',6,25,50,[OfflineRecipeIngredient(1,800),OfflineRecipeIngredient(7,500),OfflineRecipeIngredient(3,250),OfflineRecipeIngredient(4,250),OfflineRecipeIngredient(8,180),OfflineRecipeIngredient(21,35),OfflineRecipeIngredient(27,20),OfflineRecipeIngredient(12,20)]),
  OfflineRecipe(2,'Beef Biryani','برياني لحم','Beef Biryani','Pakistani',6,30,70,[OfflineRecipeIngredient(15,850),OfflineRecipeIngredient(7,500),OfflineRecipeIngredient(3,280),OfflineRecipeIngredient(4,250),OfflineRecipeIngredient(8,180),OfflineRecipeIngredient(21,40),OfflineRecipeIngredient(27,20),OfflineRecipeIngredient(12,20)]),
  OfflineRecipe(3,'Chicken Karahi','كراهي دجاج','Chicken Karahi','Pakistani',4,15,35,[OfflineRecipeIngredient(1,800),OfflineRecipeIngredient(4,500),OfflineRecipeIngredient(3,100),OfflineRecipeIngredient(26,30),OfflineRecipeIngredient(27,25),OfflineRecipeIngredient(12,20),OfflineRecipeIngredient(21,25),OfflineRecipeIngredient(28,25)]),
  OfflineRecipe(4,'Beef Karahi','كراهي لحم','Beef Karahi','Pakistani',4,15,55,[OfflineRecipeIngredient(15,800),OfflineRecipeIngredient(4,500),OfflineRecipeIngredient(3,100),OfflineRecipeIngredient(26,25),OfflineRecipeIngredient(27,25),OfflineRecipeIngredient(12,20),OfflineRecipeIngredient(21,25),OfflineRecipeIngredient(28,25)]),
  OfflineRecipe(5,'Chicken Korma','كورما دجاج','Chicken Korma','Pakistani',5,20,45,[OfflineRecipeIngredient(1,800),OfflineRecipeIngredient(8,250),OfflineRecipeIngredient(3,250),OfflineRecipeIngredient(21,40),OfflineRecipeIngredient(27,20),OfflineRecipeIngredient(12,20),OfflineRecipeIngredient(60,25)]),
  OfflineRecipe(6,'Beef Nihari','نهاري لحم','Beef Nihari','Pakistani',6,20,180,[OfflineRecipeIngredient(15,1000),OfflineRecipeIngredient(3,200),OfflineRecipeIngredient(18,30),OfflineRecipeIngredient(21,45),OfflineRecipeIngredient(27,25),OfflineRecipeIngredient(12,25)]),
  OfflineRecipe(7,'Haleem','حليم','Haleem','Pakistani',8,30,180,[OfflineRecipeIngredient(15,600),OfflineRecipeIngredient(19,180),OfflineRecipeIngredient(42,120),OfflineRecipeIngredient(41,100),OfflineRecipeIngredient(40,80),OfflineRecipeIngredient(3,250),OfflineRecipeIngredient(21,45)]),
  OfflineRecipe(8,'Aloo Gosht','بطاطا باللحم','Aloo Gosht','Pakistani',5,20,60,[OfflineRecipeIngredient(16,700),OfflineRecipeIngredient(2,650),OfflineRecipeIngredient(3,200),OfflineRecipeIngredient(4,250),OfflineRecipeIngredient(21,30),OfflineRecipeIngredient(27,20),OfflineRecipeIngredient(12,20)]),
  OfflineRecipe(9,'Keema Aloo','لحم مفروم بالبطاطا','Qeema Aloo','Pakistani',4,15,40,[OfflineRecipeIngredient(17,600),OfflineRecipeIngredient(2,500),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(4,220),OfflineRecipeIngredient(31,150),OfflineRecipeIngredient(21,20)]),
  OfflineRecipe(10,'Keema Matar','لحم مفروم بالبازلاء','Qeema Matar','Pakistani',4,15,35,[OfflineRecipeIngredient(17,600),OfflineRecipeIngredient(31,350),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(4,220),OfflineRecipeIngredient(21,20)]),
  OfflineRecipe(11,'Palak Gosht','لحم بالسبانخ','Palak Gosht','Pakistani',5,20,55,[OfflineRecipeIngredient(16,700),OfflineRecipeIngredient(14,700),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(4,200),OfflineRecipeIngredient(21,25),OfflineRecipeIngredient(12,18)]),
  OfflineRecipe(12,'Saag Chicken','دجاج بالسبانخ','Saag Chicken','Pakistani',5,20,45,[OfflineRecipeIngredient(1,700),OfflineRecipeIngredient(14,800),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(4,200),OfflineRecipeIngredient(21,25)]),
  OfflineRecipe(13,'Chana Masala','حمص ماسالا','Chana Masala','Pakistani',4,15,30,[OfflineRecipeIngredient(9,700),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(4,300),OfflineRecipeIngredient(27,15),OfflineRecipeIngredient(12,15),OfflineRecipeIngredient(10,20)]),
  OfflineRecipe(14,'Rajma Masala','فاصولياء حمراء ماسالا','Rajma Masala','Pakistani',4,15,35,[OfflineRecipeIngredient(38,700),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(4,300),OfflineRecipeIngredient(27,15),OfflineRecipeIngredient(12,15),OfflineRecipeIngredient(10,20)]),
  OfflineRecipe(15,'Moong Dal','دال ماش أخضر','Moong Dal','Pakistani',5,10,40,[OfflineRecipeIngredient(40,300),OfflineRecipeIngredient(3,150),OfflineRecipeIngredient(4,220),OfflineRecipeIngredient(12,15),OfflineRecipeIngredient(21,20)]),
  OfflineRecipe(16,'Masoor Dal','دال عدس أحمر','Masoor Dal','Pakistani',5,10,35,[OfflineRecipeIngredient(42,300),OfflineRecipeIngredient(3,150),OfflineRecipeIngredient(4,220),OfflineRecipeIngredient(12,15),OfflineRecipeIngredient(21,20)]),
  OfflineRecipe(17,'Chana Dal','دال حمص','Chana Dal','Pakistani',5,10,50,[OfflineRecipeIngredient(41,320),OfflineRecipeIngredient(3,150),OfflineRecipeIngredient(4,220),OfflineRecipeIngredient(12,15),OfflineRecipeIngredient(21,20)]),
  OfflineRecipe(18,'Dal Makhani','دال مخني','Dal Makhani','Pakistani',6,15,90,[OfflineRecipeIngredient(39,300),OfflineRecipeIngredient(38,150),OfflineRecipeIngredient(4,250),OfflineRecipeIngredient(20,35),OfflineRecipeIngredient(23,100),OfflineRecipeIngredient(3,150)]),
  OfflineRecipe(19,'Aloo Gobi','بطاطا وقرنبيط','Aloo Gobi','Pakistani',4,15,30,[OfflineRecipeIngredient(2,500),OfflineRecipeIngredient(33,600),OfflineRecipeIngredient(3,150),OfflineRecipeIngredient(4,200),OfflineRecipeIngredient(10,25)]),
  OfflineRecipe(20,'Bhindi Masala','بامية ماسالا','Bhindi Masala','Pakistani',4,15,25,[OfflineRecipeIngredient(35,700),OfflineRecipeIngredient(3,200),OfflineRecipeIngredient(4,250),OfflineRecipeIngredient(10,30)]),
  OfflineRecipe(21,'Baingan Bharta','متبل باذنجان باكستاني','Baingan Bharta','Pakistani',4,15,40,[OfflineRecipeIngredient(34,800),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(4,250),OfflineRecipeIngredient(10,25),OfflineRecipeIngredient(26,20)]),
  OfflineRecipe(22,'Chicken Pulao','بولاو دجاج','Chicken Pulao','Pakistani',6,20,45,[OfflineRecipeIngredient(1,700),OfflineRecipeIngredient(7,500),OfflineRecipeIngredient(3,220),OfflineRecipeIngredient(8,120),OfflineRecipeIngredient(21,30),OfflineRecipeIngredient(80,500)]),
  OfflineRecipe(23,'Mutton Pulao','بولاو لحم غنم','Mutton Pulao','Pakistani',6,25,70,[OfflineRecipeIngredient(16,800),OfflineRecipeIngredient(7,500),OfflineRecipeIngredient(3,220),OfflineRecipeIngredient(8,120),OfflineRecipeIngredient(21,35),OfflineRecipeIngredient(80,500)]),
  OfflineRecipe(24,'Yakhni Pulao','بولاو يخني','Yakhni Pulao','Pakistani',6,25,75,[OfflineRecipeIngredient(15,750),OfflineRecipeIngredient(7,500),OfflineRecipeIngredient(3,200),OfflineRecipeIngredient(8,100),OfflineRecipeIngredient(21,30),OfflineRecipeIngredient(80,700)]),
  OfflineRecipe(25,'Chicken Tikka','دجاج تيكا','Chicken Tikka','Pakistani',4,20,30,[OfflineRecipeIngredient(1,800),OfflineRecipeIngredient(8,200),OfflineRecipeIngredient(13,50),OfflineRecipeIngredient(27,15),OfflineRecipeIngredient(12,15),OfflineRecipeIngredient(10,15)]),
  OfflineRecipe(26,'Seekh Kebab','كباب سيخ','Seekh Kebab','Pakistani',4,20,20,[OfflineRecipeIngredient(17,700),OfflineRecipeIngredient(3,120),OfflineRecipeIngredient(28,30),OfflineRecipeIngredient(26,20),OfflineRecipeIngredient(11,50)]),
  OfflineRecipe(27,'Chapli Kebab','كباب تشابلي','Chapli Kebab','Pakistani',4,20,25,[OfflineRecipeIngredient(17,700),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(4,180),OfflineRecipeIngredient(11,50),OfflineRecipeIngredient(19,40),OfflineRecipeIngredient(10,25)]),
  OfflineRecipe(28,'Aloo Paratha','براتا بالبطاطا','Aloo Paratha','Pakistani',4,25,20,[OfflineRecipeIngredient(19,350),OfflineRecipeIngredient(2,450),OfflineRecipeIngredient(3,80),OfflineRecipeIngredient(21,35)]),
  OfflineRecipe(29,'Anda Paratha','براتا بالبيض','Anda Paratha','Pakistani',4,15,20,[OfflineRecipeIngredient(19,350),OfflineRecipeIngredient(11,200),OfflineRecipeIngredient(21,35)]),
  OfflineRecipe(30,'Kheer','أرز بالحليب الباكستاني','Kheer','Pakistani',6,10,45,[OfflineRecipeIngredient(22,1200),OfflineRecipeIngredient(7,120),OfflineRecipeIngredient(66,120),OfflineRecipeIngredient(60,30),OfflineRecipeIngredient(58,40)]),
  OfflineRecipe(31,'Mujaddara','مجدرة','Mujaddara','Syrian',5,10,45,[OfflineRecipeIngredient(5,250),OfflineRecipeIngredient(7,180),OfflineRecipeIngredient(3,350),OfflineRecipeIngredient(10,35)]),
  OfflineRecipe(32,'Mujaddara with Bulgur','مجدرة بالبرغل','Mujaddara Bulgur','Syrian',5,10,45,[OfflineRecipeIngredient(5,250),OfflineRecipeIngredient(6,220),OfflineRecipeIngredient(3,350),OfflineRecipeIngredient(10,35)]),
  OfflineRecipe(33,'Shish Barak','شيش برك','Shish Barak','Syrian',6,45,35,[OfflineRecipeIngredient(18,400),OfflineRecipeIngredient(17,350),OfflineRecipeIngredient(3,120),OfflineRecipeIngredient(8,1000),OfflineRecipeIngredient(12,20),OfflineRecipeIngredient(28,20),OfflineRecipeIngredient(10,15)]),
  OfflineRecipe(34,'Kibbeh Bil Sanieh','كبة بالصينية','Kibbeh Bil Sanieh','Syrian',6,35,45,[OfflineRecipeIngredient(6,350),OfflineRecipeIngredient(17,800),OfflineRecipeIngredient(3,250),OfflineRecipeIngredient(10,35),OfflineRecipeIngredient(59,60)]),
  OfflineRecipe(35,'Fried Kibbeh','كبة مقلية','Fried Kibbeh','Syrian',6,50,30,[OfflineRecipeIngredient(6,350),OfflineRecipeIngredient(17,800),OfflineRecipeIngredient(3,250),OfflineRecipeIngredient(10,80),OfflineRecipeIngredient(59,50)]),
  OfflineRecipe(36,'Kibbeh Labaniyeh','كبة لبنية','Kibbeh Labaniyeh','Syrian',6,45,45,[OfflineRecipeIngredient(6,300),OfflineRecipeIngredient(17,600),OfflineRecipeIngredient(3,150),OfflineRecipeIngredient(8,1200),OfflineRecipeIngredient(12,18),OfflineRecipeIngredient(28,20)]),
  OfflineRecipe(37,'Yalanji','يلنجي','Yalanji','Syrian',6,40,60,[OfflineRecipeIngredient(7,320),OfflineRecipeIngredient(4,350),OfflineRecipeIngredient(3,220),OfflineRecipeIngredient(29,100),OfflineRecipeIngredient(30,40),OfflineRecipeIngredient(13,100),OfflineRecipeIngredient(10,60)]),
  OfflineRecipe(38,'Mahshi Kousa','محشي كوسا','Mahshi Kousa','Syrian',6,35,60,[OfflineRecipeIngredient(36,1200),OfflineRecipeIngredient(7,300),OfflineRecipeIngredient(17,350),OfflineRecipeIngredient(63,80),OfflineRecipeIngredient(10,25)]),
  OfflineRecipe(39,'Mahshi Eggplant','محشي باذنجان','Mahshi Baingan','Syrian',6,35,60,[OfflineRecipeIngredient(34,1200),OfflineRecipeIngredient(7,300),OfflineRecipeIngredient(17,350),OfflineRecipeIngredient(63,80),OfflineRecipeIngredient(10,25)]),
  OfflineRecipe(40,'Dawood Basha','داوود باشا','Dawood Basha','Syrian',5,25,45,[OfflineRecipeIngredient(17,700),OfflineRecipeIngredient(3,250),OfflineRecipeIngredient(4,400),OfflineRecipeIngredient(63,60),OfflineRecipeIngredient(61,30),OfflineRecipeIngredient(10,25)]),
  OfflineRecipe(41,'Shakriyeh','شاكرية','Shakriyeh','Syrian',6,20,70,[OfflineRecipeIngredient(16,800),OfflineRecipeIngredient(8,1200),OfflineRecipeIngredient(3,150),OfflineRecipeIngredient(11,50),OfflineRecipeIngredient(7,400)]),
  OfflineRecipe(42,'Fatteh Hummus','فتة حمص','Fatteh Hummus','Syrian',5,20,15,[OfflineRecipeIngredient(9,650),OfflineRecipeIngredient(8,500),OfflineRecipeIngredient(48,250),OfflineRecipeIngredient(62,100),OfflineRecipeIngredient(12,15),OfflineRecipeIngredient(10,25),OfflineRecipeIngredient(61,30)]),
  OfflineRecipe(43,'Hummus','حمص بالطحينة','Hummus','Syrian',6,10,5,[OfflineRecipeIngredient(9,700),OfflineRecipeIngredient(62,160),OfflineRecipeIngredient(13,80),OfflineRecipeIngredient(12,15),OfflineRecipeIngredient(10,25)]),
  OfflineRecipe(44,'Baba Ghanoush','بابا غنوج','Baba Ghanoush','Syrian',5,15,35,[OfflineRecipeIngredient(34,900),OfflineRecipeIngredient(62,100),OfflineRecipeIngredient(13,70),OfflineRecipeIngredient(12,15),OfflineRecipeIngredient(10,25)]),
  OfflineRecipe(45,'Muhammara','محمرة','Muhammara','Syrian',6,15,10,[OfflineRecipeIngredient(25,700),OfflineRecipeIngredient(59,180),OfflineRecipeIngredient(48,100),OfflineRecipeIngredient(10,40),OfflineRecipeIngredient(13,30)]),
  OfflineRecipe(46,'Tabbouleh','تبولة','Tabbouleh','Syrian',6,25,0,[OfflineRecipeIngredient(29,500),OfflineRecipeIngredient(4,450),OfflineRecipeIngredient(6,100),OfflineRecipeIngredient(3,120),OfflineRecipeIngredient(30,50),OfflineRecipeIngredient(13,120),OfflineRecipeIngredient(10,50)]),
  OfflineRecipe(47,'Fattoush','فتوش','Fattoush','Syrian',6,20,5,[OfflineRecipeIngredient(4,450),OfflineRecipeIngredient(24,400),OfflineRecipeIngredient(37,250),OfflineRecipeIngredient(25,180),OfflineRecipeIngredient(3,100),OfflineRecipeIngredient(48,180),OfflineRecipeIngredient(13,100),OfflineRecipeIngredient(10,45)]),
  OfflineRecipe(48,'Syrian Lentil Soup','شوربة عدس سورية','Shorbat Adas','Syrian',6,10,35,[OfflineRecipeIngredient(42,350),OfflineRecipeIngredient(3,150),OfflineRecipeIngredient(32,150),OfflineRecipeIngredient(2,200),OfflineRecipeIngredient(10,20),OfflineRecipeIngredient(13,60)]),
  OfflineRecipe(49,'Freekeh Chicken','فريكة بالدجاج','Freekeh Chicken','Syrian',6,20,55,[OfflineRecipeIngredient(6,500),OfflineRecipeIngredient(1,800),OfflineRecipeIngredient(3,200),OfflineRecipeIngredient(21,30),OfflineRecipeIngredient(60,50),OfflineRecipeIngredient(80,700)]),
  OfflineRecipe(50,'Maqluba','مقلوبة','Maqluba','Syrian',6,30,65,[OfflineRecipeIngredient(7,500),OfflineRecipeIngredient(1,700),OfflineRecipeIngredient(34,600),OfflineRecipeIngredient(33,500),OfflineRecipeIngredient(2,300),OfflineRecipeIngredient(10,50)]),
  OfflineRecipe(51,'Kousa Bil Laban','كوسا باللبن','Kousa Bil Laban','Syrian',6,35,55,[OfflineRecipeIngredient(36,1200),OfflineRecipeIngredient(17,350),OfflineRecipeIngredient(7,180),OfflineRecipeIngredient(8,1100),OfflineRecipeIngredient(12,18)]),
  OfflineRecipe(52,'Loubieh Bil Zeit','لوبية بالزيت','Loubieh Bil Zeit','Syrian',5,15,40,[OfflineRecipeIngredient(71,900),OfflineRecipeIngredient(4,500),OfflineRecipeIngredient(3,200),OfflineRecipeIngredient(12,15),OfflineRecipeIngredient(10,50)]),
  OfflineRecipe(53,'Bamieh Bil Lahmeh','بامية باللحمة','Bamieh Lahmeh','Syrian',5,20,60,[OfflineRecipeIngredient(35,700),OfflineRecipeIngredient(16,600),OfflineRecipeIngredient(4,450),OfflineRecipeIngredient(63,60),OfflineRecipeIngredient(12,20),OfflineRecipeIngredient(10,25)]),
  OfflineRecipe(54,'Fasoulia White Bean Stew','فاصولياء بيضاء باللحمة','Fasoulia','Syrian',6,20,75,[OfflineRecipeIngredient(70,800),OfflineRecipeIngredient(15,600),OfflineRecipeIngredient(4,400),OfflineRecipeIngredient(63,70),OfflineRecipeIngredient(3,150),OfflineRecipeIngredient(10,20)]),
  OfflineRecipe(55,'Makdous','مكدوس','Makdous','Syrian',8,45,15,[OfflineRecipeIngredient(34,1000),OfflineRecipeIngredient(59,250),OfflineRecipeIngredient(25,300),OfflineRecipeIngredient(12,40),OfflineRecipeIngredient(10,300)]),
  OfflineRecipe(56,'Manakish Zaatar Style','مناقيش زعتر','Manakish','Syrian',6,40,15,[OfflineRecipeIngredient(18,600),OfflineRecipeIngredient(10,80),OfflineRecipeIngredient(13,10)]),
  OfflineRecipe(57,'Cheese Manakish','مناقيش جبنة','Cheese Manakish','Syrian',6,40,15,[OfflineRecipeIngredient(18,600),OfflineRecipeIngredient(52,300),OfflineRecipeIngredient(51,200),OfflineRecipeIngredient(10,30)]),
  OfflineRecipe(58,'Arayes','عرايس','Arayes','Syrian',6,20,20,[OfflineRecipeIngredient(48,600),OfflineRecipeIngredient(17,600),OfflineRecipeIngredient(3,150),OfflineRecipeIngredient(4,150),OfflineRecipeIngredient(29,40),OfflineRecipeIngredient(10,30)]),
  OfflineRecipe(59,'Shawarma Chicken Plate','شاورما دجاج','Chicken Shawarma','Syrian',5,25,30,[OfflineRecipeIngredient(1,800),OfflineRecipeIngredient(8,150),OfflineRecipeIngredient(13,70),OfflineRecipeIngredient(12,20),OfflineRecipeIngredient(10,30),OfflineRecipeIngredient(48,350)]),
  OfflineRecipe(60,'Rice Pudding Syrian Style','رز بحليب','Riz bi Haleeb','Syrian',6,10,35,[OfflineRecipeIngredient(22,1200),OfflineRecipeIngredient(7,130),OfflineRecipeIngredient(66,100),OfflineRecipeIngredient(60,25)]),
  OfflineRecipe(61,'Spaghetti Bolognese','سباغيتي بولونيز','Spaghetti Bolognese','European',5,15,45,[OfflineRecipeIngredient(47,450),OfflineRecipeIngredient(17,600),OfflineRecipeIngredient(4,500),OfflineRecipeIngredient(63,80),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(10,25),OfflineRecipeIngredient(53,60)]),
  OfflineRecipe(62,'Pasta Carbonara','باستا كاربونارا','Pasta Carbonara','European',4,10,25,[OfflineRecipeIngredient(47,400),OfflineRecipeIngredient(11,180),OfflineRecipeIngredient(53,100),OfflineRecipeIngredient(78,180),OfflineRecipeIngredient(10,10)]),
  OfflineRecipe(63,'Pasta Primavera','باستا بالخضار','Pasta Primavera','European',4,15,25,[OfflineRecipeIngredient(47,400),OfflineRecipeIngredient(36,250),OfflineRecipeIngredient(25,220),OfflineRecipeIngredient(73,250),OfflineRecipeIngredient(4,250),OfflineRecipeIngredient(10,30),OfflineRecipeIngredient(53,50)]),
  OfflineRecipe(64,'Margherita Pizza','بيتزا مارغريتا','Margherita Pizza','European',4,45,18,[OfflineRecipeIngredient(18,450),OfflineRecipeIngredient(4,350),OfflineRecipeIngredient(52,250),OfflineRecipeIngredient(10,25)]),
  OfflineRecipe(65,'Mushroom Pizza','بيتزا بالفطر','Mushroom Pizza','European',4,45,18,[OfflineRecipeIngredient(18,450),OfflineRecipeIngredient(4,300),OfflineRecipeIngredient(52,250),OfflineRecipeIngredient(72,250),OfflineRecipeIngredient(10,25)]),
  OfflineRecipe(66,'Chicken Risotto','ريزوتو بالدجاج','Chicken Risotto','European',5,15,40,[OfflineRecipeIngredient(7,400),OfflineRecipeIngredient(1,500),OfflineRecipeIngredient(3,150),OfflineRecipeIngredient(72,250),OfflineRecipeIngredient(20,30),OfflineRecipeIngredient(53,80),OfflineRecipeIngredient(80,700)]),
  OfflineRecipe(67,'Mushroom Risotto','ريزوتو بالفطر','Mushroom Risotto','European',5,15,40,[OfflineRecipeIngredient(7,400),OfflineRecipeIngredient(72,500),OfflineRecipeIngredient(3,150),OfflineRecipeIngredient(20,35),OfflineRecipeIngredient(53,90),OfflineRecipeIngredient(80,700)]),
  OfflineRecipe(68,'Lasagna','لازانيا','Lasagna','European',6,30,55,[OfflineRecipeIngredient(47,500),OfflineRecipeIngredient(17,700),OfflineRecipeIngredient(4,500),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(52,250),OfflineRecipeIngredient(53,80),OfflineRecipeIngredient(22,500),OfflineRecipeIngredient(20,30),OfflineRecipeIngredient(18,30)]),
  OfflineRecipe(69,'Chicken Parmesan','دجاج بارميزان','Chicken Parmesan','European',4,20,35,[OfflineRecipeIngredient(1,700),OfflineRecipeIngredient(48,150),OfflineRecipeIngredient(11,100),OfflineRecipeIngredient(4,350),OfflineRecipeIngredient(52,180),OfflineRecipeIngredient(53,70),OfflineRecipeIngredient(10,30)]),
  OfflineRecipe(70,'Greek Salad','سلطة يونانية','Greek Salad','European',4,15,0,[OfflineRecipeIngredient(4,450),OfflineRecipeIngredient(24,400),OfflineRecipeIngredient(25,180),OfflineRecipeIngredient(3,100),OfflineRecipeIngredient(51,180),OfflineRecipeIngredient(10,40),OfflineRecipeIngredient(13,60)]),
  OfflineRecipe(71,'Moussaka','مسقعة يونانية','Moussaka','European',6,30,60,[OfflineRecipeIngredient(34,900),OfflineRecipeIngredient(17,600),OfflineRecipeIngredient(4,400),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(2,500),OfflineRecipeIngredient(22,400),OfflineRecipeIngredient(20,30),OfflineRecipeIngredient(18,30),OfflineRecipeIngredient(50,100)]),
  OfflineRecipe(72,'Chicken Souvlaki','سوفلاكي دجاج','Chicken Souvlaki','European',4,20,20,[OfflineRecipeIngredient(1,700),OfflineRecipeIngredient(8,150),OfflineRecipeIngredient(13,60),OfflineRecipeIngredient(10,25),OfflineRecipeIngredient(24,250)]),
  OfflineRecipe(73,'Spanish Paella','باييلا إسبانية','Paella','European',6,25,45,[OfflineRecipeIngredient(7,500),OfflineRecipeIngredient(1,400),OfflineRecipeIngredient(46,350),OfflineRecipeIngredient(31,200),OfflineRecipeIngredient(25,200),OfflineRecipeIngredient(4,250),OfflineRecipeIngredient(10,35),OfflineRecipeIngredient(80,700)]),
  OfflineRecipe(74,'Spanish Tortilla','تورتيلا إسبانية','Spanish Tortilla','European',6,15,35,[OfflineRecipeIngredient(2,800),OfflineRecipeIngredient(11,350),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(10,60)]),
  OfflineRecipe(75,'Ratatouille','راتاتوي','Ratatouille','European',5,20,40,[OfflineRecipeIngredient(34,400),OfflineRecipeIngredient(36,400),OfflineRecipeIngredient(25,300),OfflineRecipeIngredient(4,500),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(10,35)]),
  OfflineRecipe(76,'French Onion Soup','شوربة البصل الفرنسية','French Onion Soup','European',5,15,55,[OfflineRecipeIngredient(3,900),OfflineRecipeIngredient(20,35),OfflineRecipeIngredient(80,1000),OfflineRecipeIngredient(48,200),OfflineRecipeIngredient(50,160)]),
  OfflineRecipe(77,'Chicken Ratatouille','دجاج مع راتاتوي','Chicken Ratatouille','European',5,20,40,[OfflineRecipeIngredient(1,650),OfflineRecipeIngredient(34,350),OfflineRecipeIngredient(36,350),OfflineRecipeIngredient(25,250),OfflineRecipeIngredient(4,400),OfflineRecipeIngredient(10,30)]),
  OfflineRecipe(78,'Beef Stroganoff','بيف ستروغانوف','Beef Stroganoff','European',5,20,45,[OfflineRecipeIngredient(15,700),OfflineRecipeIngredient(72,400),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(23,220),OfflineRecipeIngredient(20,25),OfflineRecipeIngredient(47,350)]),
  OfflineRecipe(79,'Shepherds Pie','فطيرة الراعي','Shepherds Pie','European',6,25,55,[OfflineRecipeIngredient(16,700),OfflineRecipeIngredient(2,900),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(32,250),OfflineRecipeIngredient(31,200),OfflineRecipeIngredient(20,35),OfflineRecipeIngredient(22,150)]),
  OfflineRecipe(80,'Fish and Potato Bake','سمك وبطاطا بالفرن','Fish Potato Bake','European',5,20,40,[OfflineRecipeIngredient(43,800),OfflineRecipeIngredient(2,800),OfflineRecipeIngredient(3,150),OfflineRecipeIngredient(23,180),OfflineRecipeIngredient(50,120),OfflineRecipeIngredient(10,20)]),
  OfflineRecipe(81,'Baked Salmon with Vegetables','سلمون بالخضار','Baked Salmon','European',4,15,30,[OfflineRecipeIngredient(44,700),OfflineRecipeIngredient(73,350),OfflineRecipeIngredient(32,250),OfflineRecipeIngredient(2,500),OfflineRecipeIngredient(10,30),OfflineRecipeIngredient(13,60)]),
  OfflineRecipe(82,'Tuna Pasta Salad','سلطة باستا بالتونا','Tuna Pasta Salad','European',5,15,15,[OfflineRecipeIngredient(47,400),OfflineRecipeIngredient(45,400),OfflineRecipeIngredient(24,250),OfflineRecipeIngredient(4,250),OfflineRecipeIngredient(31,150),OfflineRecipeIngredient(8,180),OfflineRecipeIngredient(13,40)]),
  OfflineRecipe(83,'Chicken Caesar Style Salad','سلطة سيزر بالدجاج','Chicken Caesar Salad','European',4,15,20,[OfflineRecipeIngredient(1,500),OfflineRecipeIngredient(37,500),OfflineRecipeIngredient(48,150),OfflineRecipeIngredient(53,70),OfflineRecipeIngredient(8,120),OfflineRecipeIngredient(13,40),OfflineRecipeIngredient(10,20)]),
  OfflineRecipe(84,'Omelette with Cheese and Mushroom','أومليت بالجبنة والفطر','Cheese Mushroom Omelette','European',2,10,10,[OfflineRecipeIngredient(11,200),OfflineRecipeIngredient(72,150),OfflineRecipeIngredient(50,70),OfflineRecipeIngredient(20,10)]),
  OfflineRecipe(85,'Porridge with Banana','شوفان بالموز','Banana Oat Porridge','European',2,5,10,[OfflineRecipeIngredient(54,120),OfflineRecipeIngredient(22,400),OfflineRecipeIngredient(56,200),OfflineRecipeIngredient(67,20)]),
  OfflineRecipe(86,'Apple Walnut Oatmeal','شوفان بالتفاح والجوز','Apple Walnut Oats','European',2,5,10,[OfflineRecipeIngredient(54,120),OfflineRecipeIngredient(22,400),OfflineRecipeIngredient(55,200),OfflineRecipeIngredient(59,30),OfflineRecipeIngredient(67,15)]),
  OfflineRecipe(87,'Vegetable Frittata','فريتاتا بالخضار','Vegetable Frittata','European',4,15,25,[OfflineRecipeIngredient(11,350),OfflineRecipeIngredient(14,200),OfflineRecipeIngredient(25,150),OfflineRecipeIngredient(3,100),OfflineRecipeIngredient(72,180),OfflineRecipeIngredient(50,80),OfflineRecipeIngredient(10,15)]),
  OfflineRecipe(88,'Broccoli Cheese Soup','شوربة بروكلي بالجبنة','Broccoli Cheese Soup','European',5,15,35,[OfflineRecipeIngredient(73,700),OfflineRecipeIngredient(3,150),OfflineRecipeIngredient(22,700),OfflineRecipeIngredient(50,180),OfflineRecipeIngredient(20,25),OfflineRecipeIngredient(18,25)]),
  OfflineRecipe(89,'Creamy Mushroom Soup','شوربة فطر بالكريمة','Mushroom Soup','European',5,15,35,[OfflineRecipeIngredient(72,700),OfflineRecipeIngredient(3,150),OfflineRecipeIngredient(80,700),OfflineRecipeIngredient(23,200),OfflineRecipeIngredient(20,25),OfflineRecipeIngredient(18,20)]),
  OfflineRecipe(90,'Vegetable Pasta Bake','معكرونة بالخضار بالفرن','Vegetable Pasta Bake','European',6,20,40,[OfflineRecipeIngredient(47,500),OfflineRecipeIngredient(36,250),OfflineRecipeIngredient(25,220),OfflineRecipeIngredient(72,250),OfflineRecipeIngredient(4,400),OfflineRecipeIngredient(52,220),OfflineRecipeIngredient(10,25)]),
  OfflineRecipe(91,'Chicken Pulao','بولاو دجاج','Chicken Pulao','Pakistani',6,20,50,[OfflineRecipeIngredient(1,750),OfflineRecipeIngredient(7,500),OfflineRecipeIngredient(3,220),OfflineRecipeIngredient(8,120),OfflineRecipeIngredient(21,30),OfflineRecipeIngredient(27,20),OfflineRecipeIngredient(12,15)]),
  OfflineRecipe(92,'Aloo Keema','بطاطا مع لحم مفروم','Aloo Qeema','Pakistani',5,15,40,[OfflineRecipeIngredient(17,650),OfflineRecipeIngredient(2,650),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(4,250),OfflineRecipeIngredient(21,25),OfflineRecipeIngredient(27,15),OfflineRecipeIngredient(12,15)]),
  OfflineRecipe(93,'Palak Chicken','دجاج بالسبانخ','Palak Chicken','Pakistani',5,20,40,[OfflineRecipeIngredient(1,700),OfflineRecipeIngredient(14,700),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(4,180),OfflineRecipeIngredient(21,25),OfflineRecipeIngredient(27,15),OfflineRecipeIngredient(12,15)]),
  OfflineRecipe(94,'Chana Masala','حمص ماسالا','Chana Masala','Pakistani',5,15,35,[OfflineRecipeIngredient(9,900),OfflineRecipeIngredient(3,200),OfflineRecipeIngredient(4,350),OfflineRecipeIngredient(10,25),OfflineRecipeIngredient(27,15),OfflineRecipeIngredient(12,15),OfflineRecipeIngredient(28,20)]),
  OfflineRecipe(95,'Rajma Chawal','رز مع فاصولياء حمراء','Rajma Chawal','Pakistani',6,15,45,[OfflineRecipeIngredient(38,850),OfflineRecipeIngredient(7,450),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(4,300),OfflineRecipeIngredient(10,25)]),
  OfflineRecipe(96,'Daal Chawal','رز مع عدس','Daal Chawal','Pakistani',6,15,40,[OfflineRecipeIngredient(42,380),OfflineRecipeIngredient(7,450),OfflineRecipeIngredient(3,160),OfflineRecipeIngredient(4,220),OfflineRecipeIngredient(21,20)]),
  OfflineRecipe(97,'Chicken Jalfrezi','جالفريزي دجاج','Chicken Jalfrezi','Pakistani',5,20,30,[OfflineRecipeIngredient(1,700),OfflineRecipeIngredient(25,350),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(4,300),OfflineRecipeIngredient(10,25),OfflineRecipeIngredient(26,20)]),
  OfflineRecipe(98,'Keema Matar','لحم مفروم مع بازلاء','Qeema Matar','Pakistani',5,15,35,[OfflineRecipeIngredient(17,650),OfflineRecipeIngredient(31,350),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(4,250),OfflineRecipeIngredient(21,25)]),
  OfflineRecipe(99,'Chicken Yakhni Rice','رز يخني بالدجاج','Chicken Yakhni Chawal','Pakistani',6,20,50,[OfflineRecipeIngredient(1,700),OfflineRecipeIngredient(7,500),OfflineRecipeIngredient(80,800),OfflineRecipeIngredient(3,160),OfflineRecipeIngredient(21,25)]),
  OfflineRecipe(100,'Vegetable Pulao','بولاو خضار','Sabzi Pulao','Pakistani',6,20,40,[OfflineRecipeIngredient(7,500),OfflineRecipeIngredient(31,220),OfflineRecipeIngredient(32,220),OfflineRecipeIngredient(33,220),OfflineRecipeIngredient(3,160),OfflineRecipeIngredient(21,25)]),
  OfflineRecipe(101,'Fasolia Bil Lahme','فاصولياء باللحمة','Fasolia bil Lahme','Syrian',6,20,55,[OfflineRecipeIngredient(70,900),OfflineRecipeIngredient(15,600),OfflineRecipeIngredient(4,450),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(10,25)]),
  OfflineRecipe(102,'Bamieh Bil Lahme','بامية باللحمة','Bamieh bil Lahme','Syrian',6,20,55,[OfflineRecipeIngredient(35,900),OfflineRecipeIngredient(15,600),OfflineRecipeIngredient(4,450),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(10,25)]),
  OfflineRecipe(103,'Kousa Bil Laban','كوسا باللبن','Kousa bil Laban','Syrian',6,30,50,[OfflineRecipeIngredient(36,1000),OfflineRecipeIngredient(17,450),OfflineRecipeIngredient(7,250),OfflineRecipeIngredient(8,900),OfflineRecipeIngredient(12,15)]),
  OfflineRecipe(104,'Shorbet Freekeh Style','شوربة فريكة','Shorbet Freekeh','Syrian',6,15,45,[OfflineRecipeIngredient(6,350),OfflineRecipeIngredient(1,450),OfflineRecipeIngredient(80,1200),OfflineRecipeIngredient(3,150)]),
  OfflineRecipe(105,'Batata Harra','بطاطا حرة','Batata Harra','Syrian',5,15,35,[OfflineRecipeIngredient(2,1000),OfflineRecipeIngredient(10,35),OfflineRecipeIngredient(12,20),OfflineRecipeIngredient(28,30),OfflineRecipeIngredient(13,50)]),
  OfflineRecipe(106,'Mfaraket Batata','مفركة بطاطا','Mfaraket Batata','Syrian',4,15,30,[OfflineRecipeIngredient(2,700),OfflineRecipeIngredient(11,300),OfflineRecipeIngredient(3,150),OfflineRecipeIngredient(10,25)]),
  OfflineRecipe(107,'Mloukhieh Style Chicken','ملوخية بالدجاج','Molokhia Chicken','Syrian',6,25,55,[OfflineRecipeIngredient(14,800),OfflineRecipeIngredient(1,700),OfflineRecipeIngredient(12,25),OfflineRecipeIngredient(28,25),OfflineRecipeIngredient(10,25)]),
  OfflineRecipe(108,'Lentil Bulgur Pilaf','برغل بالعدس','Bulgur bil Adas','Syrian',6,15,40,[OfflineRecipeIngredient(6,400),OfflineRecipeIngredient(5,300),OfflineRecipeIngredient(3,250),OfflineRecipeIngredient(10,35)]),
  OfflineRecipe(109,'Syrian White Bean Stew','يخنة فاصولياء بيضاء','Yakhnet Fasolia','Syrian',6,20,50,[OfflineRecipeIngredient(70,900),OfflineRecipeIngredient(4,450),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(15,450),OfflineRecipeIngredient(10,25)]),
  OfflineRecipe(110,'Eggplant Yogurt Salad','سلطة باذنجان باللبن','Batinjan bil Laban','Syrian',5,15,30,[OfflineRecipeIngredient(34,800),OfflineRecipeIngredient(8,450),OfflineRecipeIngredient(12,15),OfflineRecipeIngredient(13,40),OfflineRecipeIngredient(10,25)]),
  OfflineRecipe(111,'Chicken Cacciatore','دجاج كاتشاتوري','Chicken Cacciatore','European',5,20,45,[OfflineRecipeIngredient(1,750),OfflineRecipeIngredient(4,450),OfflineRecipeIngredient(25,250),OfflineRecipeIngredient(3,180),OfflineRecipeIngredient(72,250),OfflineRecipeIngredient(10,30)]),
  OfflineRecipe(112,'Vegetable Minestrone','شوربة مينيستروني بالخضار','Vegetable Minestrone','European',6,20,40,[OfflineRecipeIngredient(70,500),OfflineRecipeIngredient(32,250),OfflineRecipeIngredient(36,250),OfflineRecipeIngredient(37,250),OfflineRecipeIngredient(4,350),OfflineRecipeIngredient(47,180),OfflineRecipeIngredient(80,1000)]),
  OfflineRecipe(113,'Tuna Tomato Pasta','باستا بالتونا والطماطم','Tuna Tomato Pasta','European',5,15,25,[OfflineRecipeIngredient(47,450),OfflineRecipeIngredient(45,400),OfflineRecipeIngredient(4,450),OfflineRecipeIngredient(3,150),OfflineRecipeIngredient(10,25)]),
  OfflineRecipe(114,'Chicken Mushroom Pasta','باستا بالدجاج والفطر','Chicken Mushroom Pasta','European',5,20,30,[OfflineRecipeIngredient(47,450),OfflineRecipeIngredient(1,550),OfflineRecipeIngredient(72,350),OfflineRecipeIngredient(23,150),OfflineRecipeIngredient(3,120),OfflineRecipeIngredient(10,20)]),
  OfflineRecipe(115,'Baked Vegetable Omelette','أومليت خضار بالفرن','Baked Vegetable Omelette','European',4,15,25,[OfflineRecipeIngredient(11,400),OfflineRecipeIngredient(25,180),OfflineRecipeIngredient(14,180),OfflineRecipeIngredient(72,180),OfflineRecipeIngredient(50,80),OfflineRecipeIngredient(10,15)]),
  OfflineRecipe(116,'Salmon Pasta','باستا بالسلمون','Salmon Pasta','European',5,15,25,[OfflineRecipeIngredient(47,450),OfflineRecipeIngredient(44,500),OfflineRecipeIngredient(23,160),OfflineRecipeIngredient(14,180),OfflineRecipeIngredient(10,20)]),
  OfflineRecipe(117,'Potato Leek Soup','شوربة البطاطا والكراث','Potato Leek Soup','European',6,15,40,[OfflineRecipeIngredient(2,800),OfflineRecipeIngredient(74,350),OfflineRecipeIngredient(80,1000),OfflineRecipeIngredient(22,350),OfflineRecipeIngredient(20,25)]),
  OfflineRecipe(118,'Stuffed Bell Peppers','فليفلة محشية','Stuffed Bell Peppers','European',6,25,45,[OfflineRecipeIngredient(25,900),OfflineRecipeIngredient(17,500),OfflineRecipeIngredient(7,300),OfflineRecipeIngredient(4,350),OfflineRecipeIngredient(3,150),OfflineRecipeIngredient(52,120)]),
  OfflineRecipe(119,'Broccoli Chicken Bake','صينية بروكلي بالدجاج','Broccoli Chicken Bake','European',5,20,35,[OfflineRecipeIngredient(1,650),OfflineRecipeIngredient(73,650),OfflineRecipeIngredient(22,300),OfflineRecipeIngredient(50,140),OfflineRecipeIngredient(20,20)]),
  OfflineRecipe(120,'Mediterranean Chickpea Salad','سلطة حمص متوسطية','Mediterranean Chickpea Salad','European',5,15,0,[OfflineRecipeIngredient(9,800),OfflineRecipeIngredient(4,350),OfflineRecipeIngredient(24,300),OfflineRecipeIngredient(25,180),OfflineRecipeIngredient(51,120),OfflineRecipeIngredient(10,30),OfflineRecipeIngredient(13,50)]),

];

OfflineIngredient ingredientById(int id) => offlineIngredients.firstWhere((x) => x.id == id);


class OfflineNutrition {
  final double calories, protein, carbs, fat, fiber;
  const OfflineNutrition(this.calories, this.protein, this.carbs, this.fat, this.fiber);
}

OfflineNutrition nutritionForRecipe(OfflineRecipe recipe, {int? servings}) {
  var cal=0.0, protein=0.0, carbs=0.0, fat=0.0, fiber=0.0;
  for (final ri in recipe.ingredients) {
    final i=ingredientById(ri.ingredientId);
    final f=ri.quantityG/100.0;
    cal += i.calories*f; protein += i.protein*f; carbs += i.carbs*f; fat += i.fat*f; fiber += i.fiber*f;
  }
  final divisor=(servings ?? recipe.servings).clamp(1, 100);
  return OfflineNutrition(cal/divisor, protein/divisor, carbs/divisor, fat/divisor, fiber/divisor);
}

List<String> validateOfflineData() {
  final errors=<String>[];
  final ingredientIds=<int>{};
  final ingredientKeys=<String>{};
  for (final i in offlineIngredients) {
    if (!ingredientIds.add(i.id)) errors.add('Duplicate ingredient id: ${i.id}');
    if (!ingredientKeys.add(i.key)) errors.add('Duplicate ingredient key: ${i.key}');
    if (i.nameEn.trim().isEmpty || i.nameAr.trim().isEmpty || i.nameRo.trim().isEmpty) errors.add('Missing ingredient language: ${i.id}');
    if ([i.calories,i.protein,i.carbs,i.fat,i.fiber].any((v)=>v<0)) errors.add('Negative nutrition value: ${i.key}');
  }
  final recipeIds=<int>{}; final recipeNames=<String>{};
  for (final r in offlineRecipes) {
    if (!recipeIds.add(r.id)) errors.add('Duplicate recipe id: ${r.id}');
    if (!recipeNames.add(r.nameEn.toLowerCase())) errors.add('Duplicate recipe name: ${r.nameEn}');
    if (r.nameEn.trim().isEmpty || r.nameAr.trim().isEmpty || r.nameRo.trim().isEmpty) errors.add('Missing recipe language: ${r.id}');
    if (r.servings<=0) errors.add('Invalid servings: ${r.id}');
    if (r.prepMinutes<0 || r.cookMinutes<0) errors.add('Invalid time: ${r.id}');
    if (r.ingredients.isEmpty) errors.add('No ingredients: ${r.id}');
    for (final ri in r.ingredients) {
      if (!ingredientIds.contains(ri.ingredientId)) errors.add('Missing ingredient ${ri.ingredientId} in recipe ${r.id}');
      if (ri.quantityG<=0) errors.add('Invalid quantity in recipe ${r.id}');
    }
    if (r.ingredients.isNotEmpty && r.servings>0) {
      final n=nutritionForRecipe(r);
      if (n.calories<30 || n.calories>1500) errors.add('Calories/serving out of range (${n.calories.toStringAsFixed(0)}): ${r.id} ${r.nameEn}');
    }
  }
  return errors;
}

String normalizeOfflineIngredient(String value) {
  final v = value.trim().toLowerCase();
  const aliases = <String, String>{
    'aata':'whole_wheat_flour',
    'adrak':'ginger',
    'akhrot':'walnuts',
    'almond':'almonds',
    'almonds':'almonds',
    'aloo':'potato',
    'anda':'egg',
    'apple':'apple',
    'arroz':'rice',
    'atta':'whole_wheat_flour',
    'aubergine':'eggplant',
    'avocado':'avocado',
    'bacon':'bacon',
    'bacon, cooked':'bacon',
    'badam':'almonds',
    'baingan':'eggplant',
    'banana':'banana',
    'band gobi':'cabbage',
    'beans_white':'beans_white',
    'beef':'beef',
    'beetroot':'beetroot',
    'bell pepper':'bell_pepper',
    'bell_pepper':'bell_pepper',
    'bhindi':'okra',
    'black gram, dry':'black_gram',
    'black_gram':'black_gram',
    'bread':'bread',
    'broccoli':'broccoli',
    'brown bread':'whole_grain_bread',
    'brown lentils, dry':'lentils_brown',
    'bulgur':'bulgur',
    'bulgur, dry':'bulgur',
    'butter':'butter',
    'cabbage':'cabbage',
    'capsicum':'bell_pepper',
    'carrot':'carrot',
    'cauliflower':'cauliflower',
    'celery':'celery',
    'chakki aata':'whole_wheat_flour',
    'chana':'chickpeas',
    'chana dal':'split_chickpeas',
    'chawal':'rice',
    'cheddar cheese':'cheese',
    'cheeni':'sugar',
    'cheese':'cheese',
    'chicken':'chicken',
    'chicken breast':'chicken',
    'chicken breast, cooked':'chicken',
    'chicken/vegetable stock':'stock',
    'chickpea':'chickpeas',
    'chickpeas':'chickpeas',
    'chickpeas, cooked':'chickpeas',
    'chilgoza':'pine_nuts',
    'chukandar':'beetroot',
    'cilantro':'coriander',
    'coconut':'coconut',
    'coconut milk':'coconut_milk',
    'coconut_milk':'coconut_milk',
    'coriander':'coriander',
    'cornmeal':'cornmeal',
    'courgette':'zucchini',
    'cream':'cream',
    'cucumber':'cucumber',
    'dahi':'yogurt',
    'dates':'dates',
    'desi ghee':'ghee',
    'dhania':'coriander',
    'doodh':'milk',
    'egg':'egg',
    'eggplant':'eggplant',
    'eggs':'egg',
    'feta':'feta',
    'feta cheese':'feta',
    'fish':'fish_white',
    'fish_white':'fish_white',
    'flour':'flour',
    'french beans':'green_beans',
    'fresh coriander':'coriander',
    'fresh mint':'mint',
    'gajar':'carrot',
    'garlic':'garlic',
    'ghee':'ghee',
    'ginger':'ginger',
    'gosht':'beef',
    'green beans':'green_beans',
    'green chili':'green_chili',
    'green chilli':'green_chili',
    'green peas':'peas',
    'green_beans':'green_beans',
    'green_chili':'green_chili',
    'ground beef':'minced_beef',
    'ground beef, cooked':'minced_beef',
    'hari mirch':'green_chili',
    'heavy cream':'cream',
    'honey':'honey',
    'jai':'oats',
    'jhinga':'shrimp',
    'keema':'minced_beef',
    'kela':'banana',
    'khajoor':'dates',
    'kheera':'cucumber',
    'kidney beans':'kidney_beans',
    'kidney beans, cooked':'kidney_beans',
    'kidney_beans':'kidney_beans',
    'lamb':'lamb',
    'lamb, cooked':'lamb',
    'lean beef, cooked':'beef',
    'leek':'leek',
    'lehsan':'garlic',
    'lemon':'lemon',
    'lemon juice':'lemon',
    'lentils_brown':'lentils_brown',
    'macaroni':'pasta',
    'machhli':'fish_white',
    'maida':'flour',
    'makai aata':'cornmeal',
    'makhan':'butter',
    'masoor dal':'red_lentils',
    'masoor dal red':'red_lentils',
    'matar':'peas',
    'milk':'milk',
    'mince':'minced_beef',
    'minced beef':'minced_beef',
    'minced_beef':'minced_beef',
    'mint':'mint',
    'moong dal':'mung_beans',
    'mozzarella':'mozzarella',
    'mung beans':'mung_beans',
    'mung beans, dry':'mung_beans',
    'mung_beans':'mung_beans',
    'murghi':'chicken',
    'murgi':'chicken',
    'mushroom':'mushroom',
    'mushrooms':'mushroom',
    'mutton':'lamb',
    'nariyal':'coconut',
    'nariyal doodh':'coconut_milk',
    'nimbu':'lemon',
    'oatmeal':'oats',
    'oats':'oats',
    'oats, dry':'oats',
    'okra':'okra',
    'olive oil':'olive_oil',
    'olive_oil':'olive_oil',
    'onion':'onion',
    'onions':'onion',
    'orange':'orange',
    'palak':'spinach',
    'parmesan':'parmesan',
    'parsley':'parsley',
    'pasta':'pasta',
    'pasta, dry':'pasta',
    'peas':'peas',
    'phool gobi':'cauliflower',
    'pine nuts':'pine_nuts',
    'pine_nuts':'pine_nuts',
    'plain whole yogurt':'yogurt',
    'podina':'mint',
    'potato':'potato',
    'potatoes':'potato',
    'prawn':'shrimp',
    'pyaaz':'onion',
    'pyaz':'onion',
    'qeema':'minced_beef',
    'rajma':'kidney_beans',
    'red lentils':'red_lentils',
    'red lentils, dry':'red_lentils',
    'red_lentils':'red_lentils',
    'rice':'rice',
    'roti':'bread',
    'safed beans':'beans_white',
    'salmon':'salmon',
    'salmon, cooked':'salmon',
    'santara':'orange',
    'sausage':'sausage',
    'sausage, cooked':'sausage',
    'seb':'apple',
    'semolina':'semolina',
    'shehad':'honey',
    'shimla mirch':'bell_pepper',
    'shrimp':'shrimp',
    'shrimp, cooked':'shrimp',
    'sooji':'semolina',
    'spaghetti':'pasta',
    'spinach':'spinach',
    'split chickpeas':'split_chickpeas',
    'split chickpeas, dry':'split_chickpeas',
    'split_chickpeas':'split_chickpeas',
    'stock':'stock',
    'sugar':'sugar',
    'tahini':'tahini',
    'tamatar':'tomato',
    'tomato':'tomato',
    'tomato paste':'tomato_paste',
    'tomato_paste':'tomato_paste',
    'tomatoes':'tomato',
    'tori':'zucchini',
    'tuna':'tuna',
    'tuna, canned in water':'tuna',
    'urad dal':'black_gram',
    'walnut':'walnuts',
    'walnuts':'walnuts',
    'wheat flour':'flour',
    'white beans':'beans_white',
    'white beans, cooked':'beans_white',
    'white bread':'bread',
    'white fish':'fish_white',
    'white fish, cooked':'fish_white',
    'white rice, dry':'rice',
    'whole egg':'egg',
    'whole grain bread':'whole_grain_bread',
    'whole milk':'milk',
    'whole wheat flour':'whole_wheat_flour',
    'whole_grain_bread':'whole_grain_bread',
    'whole_wheat_flour':'whole_wheat_flour',
    'yakhni':'stock',
    'yoghurt':'yogurt',
    'yogurt':'yogurt',
    'zait zaytoon':'olive_oil',
    'zucchini':'zucchini',
    'أرز':'rice',
    'أفوكادو':'avocado',
    'باذنجان':'eggplant',
    'بارميزان':'parmesan',
    'بازلاء':'peas',
    'بازيلا':'peas',
    'بامية':'okra',
    'برتقال':'orange',
    'برغل':'bulgur',
    'بروكلي':'broccoli',
    'بصل':'onion',
    'بطاطا':'potato',
    'بطاطس':'potato',
    'بقدونس':'parsley',
    'بندورة':'tomato',
    'بيض':'egg',
    'تفاح':'apple',
    'تمر':'dates',
    'تونا':'tuna',
    'ثوم':'garlic',
    'جبن':'cheese',
    'جبنة':'cheese',
    'جبنة فيتا':'feta',
    'جزر':'carrot',
    'جمبري':'shrimp',
    'جوز':'walnuts',
    'جوز هند':'coconut',
    'حليب':'milk',
    'حليب جوز الهند':'coconut_milk',
    'حمص':'chickpeas',
    'حمص مجروش':'split_chickpeas',
    'خبز':'bread',
    'خبز أبيض':'bread',
    'خبز قمح كامل':'whole_grain_bread',
    'خيار':'cucumber',
    'دجاج':'chicken',
    'دقيق':'flour',
    'دقيق ذرة':'cornmeal',
    'رب البندورة':'tomato_paste',
    'رز':'rice',
    'روبيان':'shrimp',
    'زبادي':'yogurt',
    'زبدة':'butter',
    'زنجبيل':'ginger',
    'زهرة':'cauliflower',
    'زيت زيتون':'olive_oil',
    'سبانخ':'spinach',
    'سكر':'sugar',
    'سلمون':'salmon',
    'سمك':'fish_white',
    'سمك أبيض':'fish_white',
    'سمن':'ghee',
    'سميد':'semolina',
    'شمندر':'beetroot',
    'شوفان':'oats',
    'صنوبر':'pine_nuts',
    'طحين':'flour',
    'طحين قمح كامل':'whole_wheat_flour',
    'طحينة':'tahini',
    'طماطم':'tomato',
    'عدس أحمر':'red_lentils',
    'عدس بني':'lentils_brown',
    'عسل':'honey',
    'عصير ليمون':'lemon',
    'غنم':'lamb',
    'فاصوليا بيضاء':'beans_white',
    'فاصوليا حمراء':'kidney_beans',
    'فاصوليا خضراء':'green_beans',
    'فاصولياء بيضاء':'beans_white',
    'فاصولياء حمراء':'kidney_beans',
    'فاصولياء خضراء':'green_beans',
    'فروج':'chicken',
    'فطر':'mushroom',
    'فلفل أخضر':'green_chili',
    'فلفل رومي':'bell_pepper',
    'فليفلة':'bell_pepper',
    'قرنبيط':'cauliflower',
    'كراث':'leek',
    'كرفس':'celery',
    'كرنب':'cabbage',
    'كريمة':'cream',
    'كزبرة':'coriander',
    'كوسا':'zucchini',
    'لبن':'yogurt',
    'لحم':'beef',
    'لحم بقري':'beef',
    'لحم غنم':'lamb',
    'لحم مفروم':'minced_beef',
    'لحم مقدد':'bacon',
    'لوز':'almonds',
    'ليمون':'lemon',
    'ماش أخضر':'mung_beans',
    'ماش أسود':'black_gram',
    'مرق':'stock',
    'مشروم':'mushroom',
    'معجون طماطم':'tomato_paste',
    'معكرونة':'pasta',
    'مكرونة':'pasta',
    'ملفوف':'cabbage',
    'موز':'banana',
    'موزاريلا':'mozzarella',
    'نعناع':'mint',
    'نقانق':'sausage',
  };
  return aliases[v] ?? v;
}
